---
- hosts: webservers
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install update (apt)
      when: ansible_distribution == "Debian"
      package:
        name: apache2
        state: latest
    - name: Deploy static website
      copy:
        src: java-hello-world.war
        dest: /var/www/html
