---
- hosts: webservers
  become: yes
  become_method: sudo
  remote_user: ec2-user
  tasks:
    - name: install update (apt)
      when: ansible_distribution == "Debian"
      package:
        name: apache2
        state: latest
